spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TaskEarnersNG
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql


server:
  port: 9192
